const API=window.TASKFLOW_API_URL||"http://localhost:8000";let status="all",category="All",tasks=[];
const $=s=>document.querySelector(s);
async function api(path,opt={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json"},...opt});if(!r.ok){let x={};try{x=await r.json()}catch{}throw Error(x.detail||`Request failed (${r.status})`)}return r.status===204?null:r.json()}
function esc(s=""){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function dateText(d){return d?new Date(d+"T00:00:00").toLocaleDateString(undefined,{month:"short",day:"numeric",year:"numeric"}):"No due date"}
function render(){if(!tasks.length){$("#tasks").innerHTML='<div class="empty"><b>✓</b><h3>No tasks here</h3><p>Everything looks clear. Add a task when you are ready.</p><button id="emptyNew">+ Create task</button></div>';$("#emptyNew").onclick=openNew;return}$("#tasks").innerHTML=tasks.map(t=>`<article class="task ${t.completed?"done":""}"><button class="check ${t.completed?"checked":""}" data-act="toggle" data-id="${t.id}">${t.completed?"✓":""}</button><div class="task-main"><div class="title-row"><h3>${esc(t.title)}</h3><span class="priority ${t.priority}">${t.priority}</span></div>${t.description?`<p>${esc(t.description)}</p>`:""}<div class="meta">◷ ${dateText(t.due_date)} &nbsp; • &nbsp; ${esc(t.category)}</div></div><div class="actions"><button data-act="edit" data-id="${t.id}">Edit</button><button class="danger" data-act="delete" data-id="${t.id}">Delete</button></div></article>`).join("")}
async function load(){try{$("#error").textContent="";let p=new URLSearchParams({status,category,search:$("#search").value});tasks=await api("/api/tasks?"+p);render();let s=await api("/api/tasks/stats");$("#total").textContent=s.total;$("#active").textContent=s.active;$("#completed").textContent=s.completed;$("#overdue").textContent=s.overdue;let cats=[...new Set(tasks.map(t=>t.category))].sort();$("#category").innerHTML="<option>All</option>"+cats.map(c=>`<option>${esc(c)}</option>`).join("");$("#category").value=category}catch(e){$("#error").textContent="Could not connect to TaskFlow API: "+e.message}}
function openNew(){form.reset();$("#id").value="";$("#priority").value="medium";$("#taskCategory").value="General";$("#formTitle").textContent="Create a task";$("#dialog").showModal()}
function openEdit(t){$("#id").value=t.id;$("#title").value=t.title;$("#description").value=t.description;$("#priority").value=t.priority;$("#taskCategory").value=t.category;$("#due").value=t.due_date||"";$("#formTitle").textContent="Edit task";$("#dialog").showModal()}
$("#newTask").onclick=openNew;$("#close").onclick=()=>$("#dialog").close();$("#cancel").onclick=()=>$("#dialog").close();
$("#form").onsubmit=async e=>{e.preventDefault();let id=$("#id").value,p={title:$("#title").value.trim(),description:$("#description").value.trim(),priority:$("#priority").value,category:$("#taskCategory").value,due_date:$("#due").value||null};try{await api(id?"/api/tasks/"+id:"/api/tasks",{method:id?"PATCH":"POST",body:JSON.stringify(p)});$("#dialog").close();load()}catch(x){$("#error").textContent=x.message}}
$("#tasks").onclick=async e=>{let b=e.target.closest("[data-act]");if(!b)return;let id=+b.dataset.id,t=tasks.find(x=>x.id===id);try{if(b.dataset.act==="toggle")await api("/api/tasks/"+id,{method:"PATCH",body:JSON.stringify({completed:!t.completed})});else if(b.dataset.act==="edit")return openEdit(t);else if(b.dataset.act==="delete"&&confirm("Delete this task?"))await api("/api/tasks/"+id,{method:"DELETE"});load()}catch(x){$("#error").textContent=x.message}}
document.querySelectorAll("[data-status]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-status]").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");status=b.dataset.status;load()});$("#category").onchange=()=>{category=$("#category").value;load()};let timer;$("#search").oninput=()=>{clearTimeout(timer);timer=setTimeout(load,250)};load();
